// Auto-generated by npsr/trig/data/data.h.sol
// Use `spin generate -f` to force regeneration
#ifndef NPSR_TRIG_DATA_DATA_H
#define NPSR_TRIG_DATA_DATA_H

#include "npsr/trig/data/constants.h"
#include "npsr/trig/data/high.h"
#include "npsr/trig/data/approx.h"
#include "npsr/trig/data/reduction.h"

#endif // NPSR_TRIG_DATA_DATA_H
