// Auto-generated by npsr/trig/data/kpi16-inl.h.sol
// Use `spin sollya -f` to force regeneration
#if defined(NPSR_TRIG_DATA_KPI16_INL_H) == defined(HWY_TARGET_TOGGLE)  // NOLINT
#ifdef NPSR_TRIG_DATA_KPI16_INL_H
#undef NPSR_TRIG_DATA_KPI16_INL_H
#else
#define NPSR_TRIG_DATA_KPI16_INL_H
#endif

HWY_BEFORE_NAMESPACE();
namespace npsr::HWY_NAMESPACE::trig {
inline constexpr auto kKPi16Table = MakeLut<double>(
// High parts of sin(k·π/16) where k = 0, 1, ..., 15
{
0.0, 0x1.8f8b83c69a60bp-3, 0x1.87de2a6aea963p-2, 0x1.1c73b39ae68c8p-1, 
0x1.6a09e667f3bcdp-1, 0x1.a9b66290ea1a3p-1, 0x1.d906bcf328d46p-1, 0x1.f6297cff75cbp-1, 
0x1p0, 0x1.f6297cff75cbp-1, 0x1.d906bcf328d46p-1, 0x1.a9b66290ea1a3p-1, 
0x1.6a09e667f3bcdp-1, 0x1.1c73b39ae68c8p-1, 0x1.87de2a6aea963p-2, 0x1.8f8b83c69a60bp-3, 
},
// High parts of cos(k·π/16) where k = 0, 1, ..., 15
{
0x1p0, 0x1.f6297cff75cbp-1, 0x1.d906bcf328d46p-1, 0x1.a9b66290ea1a3p-1, 
0x1.6a09e667f3bcdp-1, 0x1.1c73b39ae68c8p-1, 0x1.87de2a6aea963p-2, 0x1.8f8b83c69a60bp-3, 
0.0, -0x1.8f8b83c69a60bp-3, -0x1.87de2a6aea963p-2, -0x1.1c73b39ae68c8p-1, 
-0x1.6a09e667f3bcdp-1, -0x1.a9b66290ea1a3p-1, -0x1.d906bcf328d46p-1, -0x1.f6297cff75cbp-1, 
},
// Lower parts of sin(k·π/16) and cos(k·π/16) packed together
// Format: bits [63:32] = cos_low, bits [31:0] = sin_low
// This packing saves 16×8 = 128 bytes of memory
{
0.0, 0x1.56217bc626d19p-56, 0x1.457e6bc672cedp-56, 0x1.9f6303c8b25ddp-60, 
-0x1.bdd34bc8bdd34p-55, 0x1.b25dd3c39f63p-55, -0x1.72ced3c7457e6p-57, -0x1.26d193c756217p-57, 
0.0, 0x1.26d193c756217p-57, 0x1.72ced3c7457e6p-57, -0x1.b25dd3c39f63p-55, 
0x1.bdd34bc8bdd34p-55, -0x1.9f6303c8b25ddp-60, -0x1.457e6bc672cedp-56, -0x1.56217bc626d19p-56, 
}

);
inline HWY_ATTR void _dummy_supress_unused_target(){}
} // namespace npsr::HWY_NAMESPACE::trig
HWY_AFTER_NAMESPACE();
#endif // NPSR_TRIG_DATA_KPI16_INL_H
