// Do not edit this file, it is generated by npsr/trig/data/small.h.py
// use `spin generate -f` to force regeneration
#ifndef NPSR_TRIG_DATA_SMALL_H_PY
#define NPSR_TRIG_DATA_SMALL_H_PY
namespace npsr::trig::data { namespace {
constexpr double kHiSinKPi16Table[] ={
    0,                    0x1.8f8b83c69a60bp-3, 0x1.87de2a6aea963p-2, 0x1.1c73b39ae68c8p-1,
    0x1.6a09e667f3bcdp-1, 0x1.a9b66290ea1a3p-1, 0x1.d906bcf328d46p-1, 0x1.f6297cff75cbp-1, 
    0x1p0,                0x1.f6297cff75cbp-1,  0x1.d906bcf328d46p-1, 0x1.a9b66290ea1a3p-1,
    0x1.6a09e667f3bcdp-1, 0x1.1c73b39ae68c8p-1, 0x1.87de2a6aea963p-2, 0x1.8f8b83c69a60bp-3,
};
constexpr double kHiCosKPi16Table[] ={
    0x1p0,                 0x1.f6297cff75cbp-1,   0x1.d906bcf328d46p-1,  0x1.a9b66290ea1a3p-1, 
    0x1.6a09e667f3bcdp-1,  0x1.1c73b39ae68c8p-1,  0x1.87de2a6aea963p-2,  0x1.8f8b83c69a60bp-3, 
    0,                     -0x1.8f8b83c69a60bp-3, -0x1.87de2a6aea963p-2, -0x1.1c73b39ae68c8p-1,
    -0x1.6a09e667f3bcdp-1, -0x1.a9b66290ea1a3p-1, -0x1.d906bcf328d46p-1, -0x1.f6297cff75cbp-1, 
};
constexpr double kPackedLowSinCosKPi16Table[] ={
    0,                      0x1.56217bc626d19p-56,  0x1.457e6bc672cedp-56,  0x1.9f6303c8b25ddp-60, 
    -0x1.bdd34bc8bdd34p-55, 0x1.b25dd3c39f63p-55,   -0x1.72ced3c7457e6p-57, -0x1.26d193c756217p-57,
    0,                      0x1.26d193c756217p-57,  0x1.72ced3c7457e6p-57,  -0x1.b25dd3c39f63p-55, 
    0x1.bdd34bc8bdd34p-55,  -0x1.9f6303c8b25ddp-60, -0x1.457e6bc672cedp-56, -0x1.56217bc626d19p-56,
};
}} // namespace {namespace}
#endif // NPSR_TRIG_DATA_SMALL_H_PY
